- name: debug message
  debug:
    msg: "Hello from ansible"

- name: printing the variable from the defaults
  debug:
    msg: "{{ bottle_name }}"

- name: Creating Docker Container
  docker:
    container_name: "Sandbox ready"
    image: "busybox"
    version: "latest"
    cmd: ["sleep", "10"]
    state: "started"
  register: res

- debug: msg="{{ res }}"
