- name: debug message
  debug:
    msg: "Hello from ansible"

- name: printing the variable from the defaults
  debug:
    msg: "{{ bottle_name }}"

- name: Creating Docker Container
  docker:
    container_name: "Sandbox_ready"
    image: "nginx"
    version: "latest"
    state: "absent"
    ports: "8080:80"
  register: res

- debug: msg="{{ res }}"
